#Login Page Elements
txt_UserName="name=username"
txt_Password="name=password"
btn_Login="xpath=//button[contains(text(), 'Connexion')]"

#Dashboard Page Elements
lbl_Title="xpath=//h1[@id='HEADER_TITLE']/span"
link_HeaderAccueil="id=HEADER_HOME"
link_HeaderMesFichier="id=HEADER_MY_FILES"
link_HeaderFichiersPartages="id=HEADER_SHARED_FILES_text"
link_HeaderSites="id:HEADER_SITES_MENU_text"
link_HeaderMesSites="id=HEADER_SITES_MENU_MY_SITES"
link_HeaderRechercheDeSites="id=HEADER_SITES_MENU_SITE_FINDER"
link_HeaderCreerUnSite="//*[@id='HEADER_SITES_MENU_CREATE_SITE_text']"
link_HeaderFavoris="id=HEADER_SITES_MENU_FAVOURITES"
link_HeaderTaches="id=HEADER_TASKS"
link_HeaderMesTaches="id=HEADER_MY_TASKS"
link_HeaderWorkflows="id=HEADER_MY_WORKFLOWS"
link_HeaderPersonnes="id=HEADER_PEOPLE"
link_HeaderEntrepot="id=HEADER_REPOSITORY"
link_headerOutilsAdmin="xpath=//div[@id='HEADER_ADMIN_CONSOLE']/span/a"
link_HeaderUserMenu="id=HEADER_USER_MENU_POPUP"
link_HeaderTableauDeBordUtilisateur="id=HEADER_USER_MENU_DASHBOARD"
link_HeaderMonProfil="id=HEADER_USER_MENU_PROFILE"
link_HeaderAide="id=HEADER_USER_MENU_HELP"
link_HeaderUtiliserLaPageActuelle="id=HEADER_USER_MENU_SET_CURRENT_PAGE_AS_HOME"
link_HeaderUtiliserMonTableauDeBord="id=HEADER_USER_MENU_SET_DASHBOARD_AS_HOME"
link_HeaderChangerLeMotDePasse="id=HEADER_USER_MENU_CHANGE_PASSWORD"
link_HeaderDeconnexion="id=HEADER_USER_MENU_LOGOUT"
img_Loupe="id=HEADER_SEARCH_BOX_DROPDOWN_MENU"
link_RechercheAvancee="id=HEADER_SEARCH_BOX_ADVANCED_SEARCH_text"
img_RoueDentee="id=HEADER_TITLE_MENU"
btn_Masquer="//button[text()='Masquer']"
btn_Ok="//button[text()='OK']"
btn_Annuler="//button[text()='Annuler']"
link_RechercherSite="//input[@id='template_x002e_site-finder_x002e_site-finder_x0023_default-term']"
btn_Rechercher="//button[text()='Rechercher']"

#MonProfil Page Elements
link_HeaderCorbeille="id=template_x002e_toolbar_x002e_user-profile_x0023_default-user-trashcan-link"
txt_CorbeilleSearch="id=template_x002e_user-trashcan_x002e_user-trashcan_x0023_default-search-text"
btn_CorbeilleSearch="id=template_x002e_user-trashcan_x002e_user-trashcan_x0023_default-search-button-button"
chk_CorbeilleSite="xpath=//div[text()='urlmonsite']/ancestor::tr/td/div/input"
btn_CorbeilleSiteSupprimer="xpath=//div[text()='urlmonsite']/ancestor::tr/td/div/span/span/span/button[text()='Supprimer']"
btn_CorbeilleSiteSupprimerOK="xpath=//button[text()='OK']"

#Dashbord Config page elements
btn_ChangerDisposition="id=template_x002e_customise-layout_x002e_customise-user-dashboard_x0023_default-change-button-button"
btn_Mode="id=template_x002e_customise-layout_x002e_customise-user-dashboard_x0023_default-select-button-dashboard"
btn_ChangerDisposition_OK="id=template_x002e_customise-dashlets_x002e_customise-user-dashboard_x0023_default-save-button-button"